### ISSUE TITLE
Generate webmanifest images

### ISSUE THREAD

**Issue by franzwilding** [RafidMuhymin/astro-imagetools#30] opened 2022-04-09 13:54 UTC
I'm trying to use this plugin to generate a favicon and webmanifest icons and I come to this working solution: 

First of all I import the icon in different sizes without using the import result anywhere (so the icons will get generated in different sizes): 
```
---
import Favicon from '../assets/logo.png?w=64&format=ico';
import Icon48 from '../assets/logo.png?w=48&format=png';
import Icon72 from '../assets/logo.png?w=72&format=png';
import Icon96 from '../assets/logo.png?w=96&format=png';
import Icon144 from '../assets/logo.png?w=144&format=png';
import Icon168 from '../assets/logo.png?w=168&format=png';
import Icon192 from '../assets/logo.png?w=192&format=png';

---
<html lang={locale}>
<head>
        ....
	<link rel="manifest" href="manifest.webmanifest" />
	<link rel="icon" type="image/x-icon" href={Favicon} />
</head>
<body>
...
</body>
</html>
```

Then I get the filename from the filesystem and use it in the (static) manifest.webmanifest file: 
```
{
    ...
    "icons": [{
      "src": "/assets/logo@48w.2106fe6c.png",
      "sizes": "48x48",
      "type": "image/png"
    }, {
      "src": "/assets/logo@72w.c4bb68f4.png",
      "sizes": "72x72",
      "type": "image/png"
    }, {
      "src": "/assets/logo@96w.d28bed5c.png",
      "sizes": "96x96",
      "type": "image/png"
    }, {
      "src": "/assets/logo@144w.f094205f.png",
      "sizes": "144x144",
      "type": "image/png"
    }, {
      "src": "/assets/logo@168w.0a076ecc.png",
      "sizes": "168x168",
      "type": "image/png"
    }, {
      "src": "/assets/logo@192w.e25558fa.png",
      "sizes": "192x192",
      "type": "image/png"
    }]
  }
```

This is working pretty good, however it would be nice to inject the asset path instead of copying it to the static webmanifest ifle. As far as I see, astro does not support any *static generated* non-html routes, otherwise it would be very easy to just create a manifest.webmanifest.astro page and generate it here

Does anyone have an idea, how to create webmanifest icon paths more easily?

**Comment by bronze** [comment] 2022-04-12 02:56
could you generate it as an astro file and copy the as manifest on your build command? a bit of a hack but...

**Comment by RafidMuhymin** [comment] 2022-04-19 11:30
@franzwilding there's actually a way to do this. Create a `manifest.webmanifest.js` file inside the `src/pages` directory and paste the following code:

```js
import Icon48 from "../assets/logo.png?w=72&format=png";
import Icon72 from "../assets/logo.png?w=72&format=png";
import Icon96 from "../assets/logo.png?w=96&format=png";
import Icon144 from "../assets/logo.png?w=144&format=png";
import Icon168 from "../assets/logo.png?w=168&format=png";
import Icon192 from "../assets/logo.png?w=192&format=png";

const manifest = {
  icons: [
    {
      src: Icon48,
      sizes: "48x48",
      type: "image/png",
    },
    {
      src: Icon72,
      sizes: "72x72",
      type: "image/png",
    },
    {
      src: Icon96,
      sizes: "96x96",
      type: "image/png",
    },
    {
      src: Icon144,
      sizes: "144x144",
      type: "image/png",
    },
    {
      src: Icon168,
      sizes: "168x168",
      type: "image/png",
    },
    {
      src: Icon192,
      sizes: "192x192",
      type: "image/png",
    },
  ],
};

export async function get() {
  return {
    body: JSON.stringify(manifest),
  };
}
```

**Comment by franzwilding** [comment] 2022-04-19 11:33
Thanks @RafidMuhymin, however I think this would render and return webmanifest live using the node server. I'm trying to find a similar solution, but during build time.

**Comment by RafidMuhymin** [comment] 2022-04-19 11:37
@franzwilding this works in build too. Astro supports this feature since `v0.23`. The problem is this feature is not documented very well. https://docs.astro.build/en/core-concepts/astro-pages/#non-html-pages

**Comment by franzwilding** [comment] 2022-04-19 11:55
Ah cool! I tried this some days ago, back than it was only working with the node server running. I will check it out with the newest beta build. I also checked the release notes but did not found any hint that this will work.

**Comment by RafidMuhymin** [comment] 2022-04-20 15:47
@franzwilding closing this issue now. Feel free to comment on this issue or ask in the Discord channel if you are facing any kind of problems related to Astro.

**Closed by RafidMuhymin** 2022-04-20 15:47 UTC
